# Translations template for glance_store.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance_store
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance_store 0.7.2.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-08-05 06:18+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: glance_store/backend.py:37
msgid "List of stores enabled"
msgstr ""

#: glance_store/backend.py:39
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'stores' config option."
msgstr ""

#: glance_store/backend.py:43
msgid ""
"Minimum interval seconds to execute updating dynamic storage capabilities"
" based on backend status then. It's not a periodic routine, the update "
"logic will be executed only when interval seconds elapsed and an "
"operation of store has triggered. The feature will be enabled only when "
"the option value greater then zero."
msgstr ""

#: glance_store/backend.py:217
#, python-format
msgid "Store for scheme %s not found"
msgstr ""

#: glance_store/backend.py:316
#, python-format
msgid ""
"The image metadata key %(key)s has an invalid type of %(type)s. Only "
"dict, list, and unicode are supported."
msgstr ""

#: glance_store/backend.py:343
#, python-format
msgid ""
"The storage driver %(driver)s returned invalid  metadata %(metadata)s. "
"This must be a dictionary type"
msgstr ""

#: glance_store/backend.py:351
#, python-format
msgid ""
"A bad metadata structure was returned from the %(driver)s storage driver:"
" %(metadata)s.  %(e)s."
msgstr ""

#: glance_store/backend.py:383
msgid "Skipping store.set_acls... not implemented."
msgstr ""

#: glance_store/driver.py:75
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr ""

#: glance_store/exceptions.py:54
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance_store/exceptions.py:58
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: glance_store/exceptions.py:63
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance_store/exceptions.py:67
#, python-format
msgid "Image %(image)s not found"
msgstr ""

#: glance_store/exceptions.py:71
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: glance_store/exceptions.py:75
#, python-format
msgid "The Store URI was malformed: %(uri)s"
msgstr ""

#: glance_store/exceptions.py:79
#, python-format
msgid "Image %(image)s already exists"
msgstr ""

#: glance_store/exceptions.py:83
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance_store/exceptions.py:88
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: glance_store/exceptions.py:92
msgid "Permission to write image storage media denied."
msgstr ""

#: glance_store/exceptions.py:96
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance_store/exceptions.py:100
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance_store/exceptions.py:104
msgid "Authorization failed."
msgstr ""

#: glance_store/exceptions.py:108
msgid "You are not authenticated."
msgstr ""

#: glance_store/exceptions.py:112 glance_store/exceptions.py:116
msgid "You are not authorized to complete this action."
msgstr ""

#: glance_store/exceptions.py:120
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance_store/exceptions.py:124
msgid "Data supplied was not valid."
msgstr ""

#: glance_store/exceptions.py:128
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: glance_store/exceptions.py:133
#, python-format
msgid "Driver %(driver_name)s could not be loaded."
msgstr ""

#: glance_store/exceptions.py:137
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: glance_store/exceptions.py:142
msgid "Deleting images from this store is not supported."
msgstr ""

#: glance_store/exceptions.py:146
msgid "Getting images from this store is not supported."
msgstr ""

#: glance_store/exceptions.py:150
#, python-format
msgid ""
"Getting images randomly from this store is not supported. Offset: "
"%(offset)s, length: %(chunk_size)s"
msgstr ""

#: glance_store/exceptions.py:155
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: glance_store/exceptions.py:160
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance_store/exceptions.py:164
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance_store/exceptions.py:168
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance_store/exceptions.py:172
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: glance_store/exceptions.py:178
msgid "Remote server where the image is present is unavailable."
msgstr ""

#: glance_store/exceptions.py:182
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance_store/exceptions.py:186
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance_store/exceptions.py:190
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance_store/exceptions.py:195
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: glance_store/exceptions.py:199
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""

#: glance_store/exceptions.py:204
msgid "No image data could be found"
msgstr ""

#: glance_store/exceptions.py:208
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance_store/exceptions.py:213
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance_store/common/auth.py:188 glance_store/common/auth.py:228
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance_store/common/auth.py:256
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance_store/common/auth.py:277
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr ""

#: glance_store/common/config.py:33
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance_store/common/config.py:39
msgid "Name of the paste configuration file."
msgstr ""

#: glance_store/common/config.py:44
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance_store/common/config.py:51
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance_store/common/config.py:59
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance_store/common/config.py:66
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""

#: glance_store/common/config.py:69
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance_store/common/config.py:72
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance_store/common/config.py:75
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance_store/common/config.py:78
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance_store/common/config.py:81
msgid "Python module path of data access API"
msgstr ""

#: glance_store/common/config.py:83
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""

#: glance_store/common/config.py:86
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance_store/common/config.py:89
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance_store/common/config.py:94
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance_store/common/config.py:99
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""

#: glance_store/common/config.py:102
msgid ""
"Set a system wide quota for every user.  This value is the total number "
"of bytes that a user can use across all storage systems.  A value of 0 "
"means unlimited."
msgstr ""

#: glance_store/common/config.py:106
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance_store/common/config.py:108
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance_store/common/config.py:110
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance_store/common/config.py:113
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance_store/common/config.py:116
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""

#: glance_store/common/config.py:202
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr ""

#: glance_store/common/config.py:213
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance_store/common/utils.py:86
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

