# Translations template for glance_store.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance_store
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance_store 0.9.2.dev14\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-22 06:28+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: glance_store/backend.py:37
msgid "List of stores enabled"
msgstr ""

#: glance_store/backend.py:39
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'stores' config option."
msgstr ""

#: glance_store/backend.py:43
msgid ""
"Minimum interval seconds to execute updating dynamic storage capabilities"
" based on backend status then. It's not a periodic routine, the update "
"logic will be executed only when interval seconds elapsed and an "
"operation of store has triggered. The feature will be enabled only when "
"the option value greater then zero."
msgstr ""

#: glance_store/backend.py:217
#, python-format
msgid "Store for scheme %s not found"
msgstr ""

#: glance_store/backend.py:316
#, python-format
msgid ""
"The image metadata key %(key)s has an invalid type of %(type)s. Only "
"dict, list, and unicode are supported."
msgstr ""

#: glance_store/backend.py:343
#, python-format
msgid ""
"The storage driver %(driver)s returned invalid  metadata %(metadata)s. "
"This must be a dictionary type"
msgstr ""

#: glance_store/backend.py:351
#, python-format
msgid ""
"A bad metadata structure was returned from the %(driver)s storage driver:"
" %(metadata)s.  %(e)s."
msgstr ""

#: glance_store/backend.py:383
msgid "Skipping store.set_acls... not implemented."
msgstr ""

#: glance_store/driver.py:69
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr ""

#: glance_store/exceptions.py:47
msgid "An unknown exception occurred"
msgstr ""

#: glance_store/exceptions.py:68
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance_store/exceptions.py:72
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: glance_store/exceptions.py:77
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance_store/exceptions.py:81
#, python-format
msgid "Image %(image)s not found"
msgstr ""

#: glance_store/exceptions.py:85
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: glance_store/exceptions.py:89
#, python-format
msgid "The Store URI was malformed: %(uri)s"
msgstr ""

#: glance_store/exceptions.py:93
#, python-format
msgid "Image %(image)s already exists"
msgstr ""

#: glance_store/exceptions.py:97
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance_store/exceptions.py:102
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: glance_store/exceptions.py:106
msgid "Permission to write image storage media denied."
msgstr ""

#: glance_store/exceptions.py:110
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance_store/exceptions.py:114
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance_store/exceptions.py:118
msgid "Authorization failed."
msgstr ""

#: glance_store/exceptions.py:122
msgid "You are not authenticated."
msgstr ""

#: glance_store/exceptions.py:126 glance_store/exceptions.py:130
msgid "You are not authorized to complete this action."
msgstr ""

#: glance_store/exceptions.py:134
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance_store/exceptions.py:138
msgid "Data supplied was not valid."
msgstr ""

#: glance_store/exceptions.py:142
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: glance_store/exceptions.py:147
#, python-format
msgid "Driver %(driver_name)s could not be loaded."
msgstr ""

#: glance_store/exceptions.py:151
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: glance_store/exceptions.py:156
msgid "Deleting images from this store is not supported."
msgstr ""

#: glance_store/exceptions.py:160
msgid "Getting images from this store is not supported."
msgstr ""

#: glance_store/exceptions.py:164
#, python-format
msgid ""
"Getting images randomly from this store is not supported. Offset: "
"%(offset)s, length: %(chunk_size)s"
msgstr ""

#: glance_store/exceptions.py:169
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: glance_store/exceptions.py:174
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance_store/exceptions.py:178
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance_store/exceptions.py:182
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance_store/exceptions.py:186
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: glance_store/exceptions.py:192
msgid "Remote server where the image is present is unavailable."
msgstr ""

#: glance_store/exceptions.py:196
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance_store/exceptions.py:200
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance_store/exceptions.py:204
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance_store/exceptions.py:209
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: glance_store/exceptions.py:213
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""

#: glance_store/exceptions.py:218
msgid "No image data could be found"
msgstr ""

#: glance_store/exceptions.py:222
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance_store/exceptions.py:227
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance_store/common/auth.py:189 glance_store/common/auth.py:229
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance_store/common/auth.py:257
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance_store/common/auth.py:278
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr ""

#: glance_store/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance_store/common/config.py:40
msgid "Name of the paste configuration file."
msgstr ""

#: glance_store/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance_store/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance_store/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance_store/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""

#: glance_store/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance_store/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance_store/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance_store/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance_store/common/config.py:82
msgid "Python module path of data access API"
msgstr ""

#: glance_store/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""

#: glance_store/common/config.py:87
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance_store/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance_store/common/config.py:95
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance_store/common/config.py:100
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""

#: glance_store/common/config.py:103
msgid ""
"Set a system wide quota for every user.  This value is the total number "
"of bytes that a user can use across all storage systems.  A value of 0 "
"means unlimited."
msgstr ""

#: glance_store/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance_store/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance_store/common/config.py:111
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance_store/common/config.py:114
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance_store/common/config.py:117
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""

#: glance_store/common/config.py:203
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr ""

#: glance_store/common/config.py:214
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance_store/common/utils.py:88
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

